general_settings:
  master_key: "sk-pasand2#"
  database_url: "postgresql://neondb_owner:npg_hQ04XngzKmaM@ep-purple-hat-a8npmf90-pooler.eastus2.azure.neon.tech/litellmproxy?sslmode=require&channel_binding=require" 
model_list:
  - model_name: azure-gpt-4o
    litellm_params:
      model: azure/<your-azure-model-deployment>
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: "2025-01-01-preview"